# Generated by Django 2.0.2 on 2019-06-22 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('W', 'waiting'), ('A', 'attended')], default='W', max_length=1, verbose_name='state')),
                ('diagnostic', models.TextField(blank=True, null=True, verbose_name='diagnostic')),
                ('treatment', models.TextField(blank=True, null=True, verbose_name='treatment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10, verbose_name='dni')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('district', models.CharField(blank=True, choices=[('aqp-1', 'ALTO SELVA ALEGRE'), ('aqp-2', 'AREQUIPA'), ('aqp-3', 'CAYMA'), ('aqp-4', 'CERRO COLORADO'), ('aqp-5', 'CHARACATO'), ('aqp-6', 'CHIGUATA'), ('aqp-7', 'JACOBO HUNTER'), ('aqp-8', 'JOSE LUIS BUSTAMANTE Y RIVERO'), ('aqp-9', 'LA JOYA'), ('aqp-10', 'MARIANO MELGAR'), ('aqp-11', 'MIRAFLORES'), ('aqp-12', 'MOLLEBAYA'), ('aqp-13', 'PAUCARPATA'), ('aqp-14', 'POCSI'), ('aqp-15', 'POLOBAYA'), ('aqp-16', 'QUEQUEÑA'), ('aqp-17', 'SABANDIA'), ('aqp-18', 'SACHACA'), ('aqp-19', 'SAN JUAN DE SIGUAS'), ('aqp-20', 'SANTA ISABEL DE SIGUAS'), ('aqp-21', 'SANTA RITA DE SIHUAS'), ('aqp-22', 'SOCABAYA'), ('aqp-23', 'TIABAYA'), ('aqp-24', 'UCHUMAYO'), ('aqp-25', 'VITOR'), ('aqp-26', 'YANAHUARA'), ('aqp-27', 'YARABAMBA'), ('aqp-28', 'YURA')], max_length=6, null=True, verbose_name='district')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('sex', models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female')], max_length=1, null=True, verbose_name='sex')),
                ('weight', models.CharField(blank=True, max_length=10, null=True, verbose_name='weight')),
                ('stature', models.CharField(blank=True, max_length=10, null=True, verbose_name='stature')),
                ('allergic', models.TextField(blank=True, null=True, verbose_name='allergic')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('blood_pressure', models.TextField(blank=True, null=True, verbose_name='blood pressure')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
            ],
        ),
        migrations.AddField(
            model_name='attention',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Patient'),
        ),
        migrations.AddField(
            model_name='attention',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Speciality'),
        ),
    ]
