# Generated by Django 2.0.2 on 2020-12-02 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, 'Ropa'), (2, 'Víveres no Perecibles'), (3, 'Agrícola'), (4, 'Juguetes'), (5, 'Bicicletas'), (6, 'Otros')], default=6, verbose_name='Producto')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Peso')),
                ('notes', models.CharField(max_length=255, verbose_name='Observaciones')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='attention',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='attention',
            name='speciality',
        ),
        migrations.DeleteModel(
            name='Attention',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Speciality',
        ),
    ]
