# Generated by Django 2.0.2 on 2020-12-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201202_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='notes',
            field=models.CharField(max_length=255, null='true', verbose_name='Observaciones'),
        ),
    ]
