# Generated by Django 2.0.2 on 2020-12-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201202_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accumulate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('clothes', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ropa')),
                ('viveres', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Viveres')),
                ('agricola', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Agricola')),
                ('toys', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Juguetes')),
                ('bicycle', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bicicletas')),
                ('bicycle_cant', models.IntegerField(blank=True, default=0, max_length=50, verbose_name='Cantidad bicicletas')),
                ('others', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Otros')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, max_length=50, verbose_name='Cantidad'),
        ),
    ]
