# Generated by Django 2.0.2 on 2020-12-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201203_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accumulate',
            name='bicycle_cant',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad bicicletas'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad'),
        ),
    ]
